version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: sigfe-postgres
    restart: always
    environment:
      POSTGRES_DB: sigfe
      POSTGRES_USER: sigfe_user
      POSTGRES_PASSWORD: sigfe_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
